### ISSUE TITLE
Doesnt 11 return 11st?

### ISSUE THREAD

**Issue by cozyplanes** [DevRant-Stats/devrant-stats.github.io#4]
According to this source, doesn't 11 returns 11st, 12 returns 12nd, and 13 returns 13rd?

https://devrant-stats.github.io/js/filter/rank.js

I am not an js dev btw...

@Skayo

**Comment by Skayo** [comment]
From my experience, it works :)
The important part is `var lastDigit = input % 10;`

**Comment by cozyplanes** [comment]
hmm, ok, interesting

`still hates js`
